### ISSUE TITLE
Throws 500 after upgrade

### ISSUE THREAD

**Issue by aticiburak46** [mnellemann/hmci#2] opened 2024-03-15 14:25 UTC
Hello,

After i upgrade my hmc to newer version this logs found in hmci -d.

In your changelog there is line that says update information in docs but i couldn't able to find it. Can you please share me how do i upgrade my hcmi service to fix this issue ?

Also, this project is quite usefull and thanks to you for doing this :) 

[ERROR] RestClient - getRequest() - Unexpected response: 500
[ERROR] LogicalPartition - refresh() - error 2: getRequest() - Unexpected response: 500

Have a great day!!

**Comment by mnellemann** [comment] 2024-03-15 16:43
Hi,

I have heard of this before, but have not been able to reproduce on my own test HMC (virtual HMC on Power LPAR v10.2).
Can you share the HMC version you are running (lshmc -V) ?


Thanks

**Comment by aticiburak46** [comment] 2024-03-18 08:58
Hello again,

Current version is : V10R3 M1050 and also im sharing the change we made in following line;

V10R1 M1020 -> V10R3 M1050

Have a great week..

**Comment by aticiburak46** [comment] 2024-04-01 12:32
Hey again,

Any news about this stuation ? 

Kind Regards

**Comment by mnellemann** [comment] 2024-04-01 14:17
Hi,

Sorry, no progress.
I will try to get my test HMC updated to V10R3 this week and test.
Will keep you updated.

Best regards

**Comment by mnellemann** [comment] 2024-04-03 12:58
Hi.

I'm not sure I will get access to a V10R3 HMC this week.

The 500 error is from the HMC and I can't see any changes to the API. Initially when HMCI is started it tries to fetch many data-points and not only the most recent. As data is processed, then only the most recent is fetched continuously every 30 sec. I have tried to lower this initial value - maybe it could be the reason for the error. Would you be able to test this with the the version which can be downloaded with the links below?

RPM version: https://cloud.data.coop/s/HkMQtndG8Xg3Spj
DEB version: https://cloud.data.coop/s/7m47M6M8RqrMzAq



Best regards,
Mark

**Comment by mnellemann** [comment] 2024-04-04 10:04
If possible, try to disable performance data collection for all systems, and then enable it again.

**Comment by aticiburak46** [comment] 2024-04-04 10:40
Hi,

Thank for your responses. DEB package and disable/enable didn't work for me. I'm still investigating why API doesn't work properly. It looks like problem does not related to your work. I also try to get data with url requests but it doesn't work too. Might be update problems or it is related to PCM.

Please let me know if you findout any reason or any solutions for this problem.

Besides this, your work is great and thank you for your efforts.. Keep it up! :) 

Kind Regards

**Comment by mnellemann** [comment] 2024-04-05 12:08
Hi,

I got my test HMC (virtual on Power) upgraded to V10R3 M1050 and everything is still working. No 500 responses from the HMC. 

Are you on a CR1, CR2 or vHMC ?


Best regards,

**Comment by aticiburak46** [comment] 2024-04-16 10:04
Hey again and sorry to take your time. We just found out problem related to postgresql database on vHcmi, API was not working properly.

We have contacted with ibm support then they shared a fix with us. After we apply fix, also applied some commands to purge database and reinitialize it. Then rest api as PCM worked perfectly. Now we are able to collect data with your services.

Really thank you for your helps. Have a great day!

Best Regards

**Comment by mnellemann** [comment] 2024-04-16 11:34
Thank you for the feedback and good to know you found a solution.
Is there any way you could share the fix with me ? :)

Best regards,
Mark

**Comment by burakbulutist** [comment] 2024-05-08 08:43
I'm sorry to late response, i have talked with my colleagues but unfortunately this fix for exclusive for us if im not mistaken. So i can not share it with you. But if you can communicate with IBM i believe they can help you.

Again thanks for all your effort and you really did great job to  create this project. Have a great jobs!

**Comment by aticiburak46** [comment] 2024-05-16 12:14
Hello again, this last comment is mine but i accidentally wrote from different account.

I have a question for you, would be great if you have a time to response me.

For some reasons, i do not get lots of metrics for a while for some hosts. Is there an any way to get this data to influxdb somehow? Because i want to check historical data and see what's going on in the environment.

Thanks,
Burak

**Comment by mnellemann** [comment] 2024-06-27 09:53
Hi Burak,

Sorry, there is no way to import historical data with this collector tool.

Closing this issue.

**Closed as completed by mnellemann** 2024-06-27 09:53 UTC
